[phases.setup]
nixPkgs = ['php83', 'php83Extensions.intl', 'php83Extensions.pdo_pgsql', 'php83Extensions.gd', 'php83Extensions.zip', 'nodejs', 'npm']

[phases.install]
cmds = [
  'npm ci',
  'composer install --optimize-autoloader --no-dev',
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'